(ns memefactory.server.constants)


(def web3-events
  {:param-change-db/eternal-db-event [:param-change-registry-db :EternalDbEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/param-change-constructed-event [:param-change-registry-fwd :ParamChangeConstructedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/challenge-created-event [:param-change-registry-fwd :ChallengeCreatedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/vote-committed-event [:param-change-registry-fwd :VoteCommittedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/vote-revealed-event [:param-change-registry-fwd :VoteRevealedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/vote-amount-claimed-event [:param-change-registry-fwd :VoteAmountClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/vote-reward-claimed-event [:param-change-registry-fwd :VoteRewardClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/challenge-reward-claimed-event [:param-change-registry-fwd :ChallengeRewardClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :param-change-registry/param-change-applied-event [:param-change-registry-fwd :ParamChangeAppliedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry-db/eternal-db-event [:meme-registry-db :EternalDbEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/meme-constructed-event [:meme-registry-fwd :MemeConstructedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/meme-minted-event [:meme-registry-fwd :MemeMintedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/challenge-created-event [:meme-registry-fwd :ChallengeCreatedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/vote-committed-event [:meme-registry-fwd :VoteCommittedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/vote-revealed-event [:meme-registry-fwd :VoteRevealedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/vote-amount-claimed-event [:meme-registry-fwd :VoteAmountClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/vote-reward-claimed-event [:meme-registry-fwd :VoteRewardClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-registry/challenge-reward-claimed-event [:meme-registry-fwd :ChallengeRewardClaimedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-auction-factory/meme-auction-started-event [:meme-auction-factory-fwd :MemeAuctionStartedEvent {} {:from-block 0 :to-block "latest"}]
   :meme-auction-factory/meme-auction-buy-event [:meme-auction-factory-fwd :MemeAuctionBuyEvent {} {:from-block 0 :to-block "latest"}]
   :meme-auction-factory/meme-auction-canceled-event [:meme-auction-factory-fwd :MemeAuctionCanceledEvent {} {:from-block 0 :to-block "latest"}]
   :meme-token/transfer [:meme-token :Transfer {} {:from-block 0 :to-block "latest"}]
   ;; :dank-faucet/not-enough-ETH [:dank-faucet :NotEnoughETH {} {:from-block 0 :to-block "latest"}]
   :dank-faucet/dank-event [:dank-faucet :DankEvent {} {:from-block 0 :to-block "latest"}]
   :dank-faucet/oraclize-call [:dank-faucet :OraclizeCall {} {:from-block 0 :to-block "latest"}]
   :dank-faucet/dank-reset [:dank-faucet :DankReset {} {:from-block 0 :to-block "latest"}]})
