(ns memefactory.shared.routes)

(def routes [["/" :route/home]
             ["/marketplace" :route.marketplace/index]
             ["/dankregistry/index" :route.dank-registry/index]
             ["/dankregistry/submit" :route.dank-registry/submit]
             ["/dankregistry/vote" :route.dank-registry/vote]
             ["/dankregistry/challenge" :route.dank-registry/challenge]
             ["/dankregistry/browse" :route.dank-registry/browse]
             ["/leaderboard/dankest" :route.leaderboard/dankest]
             ["/leaderboard/curators" :route.leaderboard/curators]
             ["/leaderboard/creators" :route.leaderboard/creators]
             ["/leaderboard/collectors" :route.leaderboard/collectors]
             ["/memefolio/:address" :route.memefolio/index]
             ["/memefolio/" :route.memefolio/index]
             ["/meme-detail/:address" :route.meme-detail/index]
             ["/get-dank" :route.get-dank/index]
             ["/my-settings" :route.my-settings/index]
             ["/about" :route.about/index]
             ["/how-it-works" :route.how-it-works/index]
             ["/privacy-policy" :route.privacy-policy/index]
             ["/param-change" :route.param-change/index]
             ["/terms-of-use" :route.terms/index]
             ])
